import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // src/contracts is generated by `npm run contracts:sync` and is guarded by
  // `npm run contracts:check` instead — linting it would report on code that
  // cannot be edited here (Section 2.4).
  globalIgnores(['dist', 'src/contracts']),
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      // No debug logging left in committed code (Section 9.1).
      'no-console': 'error',
    },
  },
  {
    // Vitest files run in jsdom but also use node globals for setup.
    files: ['**/*.test.{js,jsx}', 'src/lib/test-setup.js'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
])
